//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Entidad;
    
    public partial class ReportesDBEntities : DbContext
    {
        public ReportesDBEntities()
            : base("name=ReportesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual DbSet<REPORTES> REPORTES { get; set; }
    
        public virtual int GuardarEmpleado(string nombre, string apellido, string contraseña, string correo, string cargo, Nullable<int> id_departamento)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var contraseñaParameter = contraseña != null ?
                new ObjectParameter("contraseña", contraseña) :
                new ObjectParameter("contraseña", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var cargoParameter = cargo != null ?
                new ObjectParameter("cargo", cargo) :
                new ObjectParameter("cargo", typeof(string));
    
            var id_departamentoParameter = id_departamento.HasValue ?
                new ObjectParameter("id_departamento", id_departamento) :
                new ObjectParameter("id_departamento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarEmpleado", nombreParameter, apellidoParameter, contraseñaParameter, correoParameter, cargoParameter, id_departamentoParameter);
        }
    
        public virtual int CrearDepartamento(string nombre, string siglas)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var siglasParameter = siglas != null ?
                new ObjectParameter("siglas", siglas) :
                new ObjectParameter("siglas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CrearDepartamento", nombreParameter, siglasParameter);
        }
    
        public virtual int GuardarReporte(Nullable<int> idEmpleado, string nombreReporte, Nullable<int> depatamentoDestino)
        {
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("idEmpleado", idEmpleado) :
                new ObjectParameter("idEmpleado", typeof(int));
    
            var nombreReporteParameter = nombreReporte != null ?
                new ObjectParameter("nombreReporte", nombreReporte) :
                new ObjectParameter("nombreReporte", typeof(string));
    
            var depatamentoDestinoParameter = depatamentoDestino.HasValue ?
                new ObjectParameter("depatamentoDestino", depatamentoDestino) :
                new ObjectParameter("depatamentoDestino", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GuardarReporte", idEmpleadoParameter, nombreReporteParameter, depatamentoDestinoParameter);
        }
    }
}
